apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-manager-deployment
  labels:
    app: coupon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-manager
  template:
    metadata:
      labels:
        app: coupon-manager
    spec:
      containers:
      - name: coupon-manager-api
        image: coupon-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: S3_ENDPOINT_URL
          value: "http://127.0.0.1:4566"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
<<<<<<< HEAD
          valueFrom:
            configMapKeyRef:
              name: coupon-manager-config
              key: AWS_DEFAULT_REGION
=======
          value: "us-east-1"
      - name: localstack
        image: localstack/localstack:3.2
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: "s3"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
>>>>>>> 1e6aeb7 (fix: refactor to sidecar pattern with localstack and update frontend api endpoint)
